spec/03_number_spec.rb : Fix comment in Assignment
TheOdinProject/ruby_testing pull request #34
Opened 2022-09-18 09:07 UTC by Uaitt

The lesson  talks about the use of the method subject and the differences between subject and let. The comment in question tells the user to create a variable (an helper method actually) with let, while I believe it should be created with subject, because: 1) subject is the topic of the lesson;
2) the variable we are creating is the subject of all the tests, hence it makes more sense to create it with subject instead of let.

Complete the following REQUIRED checkboxes:

-   [x] I have thoroughly read and understand [The Odin Project Contributing Guide](https://github.com/TheOdinProject/theodinproject/blob/main/CONTRIBUTING.md)
-   [x] The title of this PR follows the `location of change: brief description of change` format, e.g. `String spec: Update instructions for clarity`

Complete the following checkboxes ONLY IF they are applicable to your PR. You can complete them later if they are not currently applicable:
-   [ ] I have ensured any exercise files included in this PR have passed all of their tests

<hr>

**1. Because:**

Closes #XXXXX

**2. This PR:**

**3. Additional Information:**

2022-09-19 02:57 UTC, rlmoser99 requested changes
This change would also need changes in the corresponding spec_answer file.

2022-09-20 11:53 UTC, Uaitt reviewed
Done.

2022-09-20 12:52 UTC, rlmoser99 requested changes
Thanks for updating this PR so quickly. We need 1 more change in the file in spec_answer.

2022-09-20 12:52 UTC, rlmoser99 commented on spec_answers/03_number_answer.rb
>      let(:my_array) { [-7, 42, 101, 98] }
```suggestion
    subject(:my_array) { [-7, 42, 101, 98] }
```

2022-09-20 13:21 UTC, Uaitt commented on spec_answers/03_number_answer.rb
>      let(:my_array) { [-7, 42, 101, 98] }
Fixed! Sorry for the inconvenience.

2022-09-20 23:53 UTC, rlmoser99 approved these changes
Thank you for taking the time to made & update this PR.

2022-09-20 23:55 UTC, merged